# CI/CD * DEPLOYMENT * TO * PRODUCTION #####################################################################
variables:
  BIND_FILE_UPLOADED_DEV: "/root/data/development/portofolio/uploads" # Path to the uploaded files
  # FOR PRODUCTIONS
  BIND_FILE_UPLOADED_PROD: "/root/data/production/portofolio/uploads" # Path to the uploaded files
stages:
  - prebuild
build_production:
  stage: prebuild
  when: manual
  only:
    - main
  tags:
    - portofolio-be # Ganti dengan tag runner Anda jika diperlukan
  script:
    - docker build -t dev-backend-portofolio:latest .
    - sudo ufw allow 27017
    - docker stop be-portofolio-dev && docker rm be-portofolio-dev
    - docker run -d -p 9000:9000 --name be-portofolio-dev -v /root/data/production/portofolio/uploads:/app/uploads dev-backend-portofolio:latest
    - sleep 3
    - sudo ufw deny 27017