version: "3.8"

services:
  node-app:
    build:
      context: .
      dockerfile: ${DOCKER_FILENAME}
    image: node-app
    ports:
      - "9000:9000"
    volumes:
      - /root/data/production/portofolio/uploads:/app/uploads
    networks:
      - mongoCluster
networks:
  mongoCluster:
    driver: bridge